const ACTION_TYPES = {
  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',

  SELECT_CHAT_ACTION: 'SELECT_CHAT_ACTION',

  LOAD_CHATS_REQUEST: 'LOAD_CHAT_LIST_REQUEST',
  LOAD_CHATS_SUCCESS: 'LOAD_CHAT_LIST_SUCCESS',
  LOAD_CHATS_ERROR: 'LOAD_CHAT_LIST_ERROR',

  CREATE_CHAT_REQUEST: 'CREATE_CHAT_REQUEST',
  CREATE_CHAT_SUCCESS: 'CREATE_CHAT_SUCCESS',
  CREATE_CHAT_ERROR: 'CREATE_CHAT_ERROR',

  LOAD_CHAT_MESSAGES_REQUEST: 'LOAD_CHAT_MESSAGES_REQUEST',
  LOAD_CHAT_MESSAGES_SUCCESS: 'LOAD_CHAT_MESSAGES_SUCCESS',
  LOAD_CHAT_MESSAGES_ERROR: 'LOAD_CHAT_MESSAGES_ERROR',

  LOAD_NEW_MESSAGE_REQUEST: 'LOAD_NEW_MESSAGE_REQUEST',

  JOIN_TO_CHAT_REQUEST: 'JOIN_TO_CHAT_REQUEST',
  JOIN_TO_CHAT_SUCCESS: 'JOIN_TO_CHAT_SUCCESS',
  JOIN_TO_CHAT_ERROR: 'JOIN_TO_CHAT_ERROR',

  ADD_TYPING_PERSON_REQUEST: 'ADD_TYPING_PERSONS_REQUEST',
  DELETE_TYPING_PERSON_REQUEST: 'DELETE_TYPING_PERSON_REQUEST',

};

export default ACTION_TYPES;